KWARC/rust-libxml

Cargo.lock
src/parser.rs
src/tree.rs
src/xpath.rs
tests/base_tests.rs

The basic issue here was that we were casting to a pointer as a chain call on ```CString::new```, which in the latest nightly seems to result into null pointers by the time they are passed into libxml.
The refacotoring here fixes that, and we should be able to merge the PR that adds support for Rust stable next ( #2 ).
@jfschaefer let me know if you don't want to maintain the repo / are short on time, if you give me commit access I can push directly into the repo. Or we can move it to the KWARC org, up to you.

Compat for Rust nightly 22.02: hold CString::new results in var

---

src/xpath.rs
tests/base_tests.rs

First commit has test, which demonstrates segmentation fault, second commit fixes error and makes that test impossible to compile, so test is removed in second commit. This change also makes #8 impossible to compile, so that was the real cause of problem there.

Doc out of scope

---

src/c_signatures.rs
src/parser.rs

This is mainly for suppressing warnings, which libxml write to stderr, they really on the way in console application.

Use the same options for parse_string() as in parse_file()

---

src/c_signatures.rs
src/helper_functions.c
src/helper_functions.h
src/tree.rs
tests/base_tests.rs

Coming from ruby I've loved to use Nokogiri, so now that I'm porting some code I found that this wasn't in libxml but in Nokogiri but still think it is useful.
From the Nokogiri docs
> This could be useful for developers who either don't understand namespaces
or don't care about them.

Add ability to recursively remove ns

---

build.rs
src/helper_functions.c

As I'm using a local repo I get a warning each time I compile, this silence that warning a alas doesn't clobber my tiny console output.

Add attribute for gcc about unused variable

---

.rustfmt.toml
src/c_signatures.rs
src/global.rs
src/parser.rs
src/tree.rs
src/xpath.rs
tests/base_tests.rs

Cosmetic changes, and a "lightweight" breaking change to the namespace argument calls
* Added a custom rustfmt rule for tab_spaces being 2. It's an endless point of disagreement, and just fits my visual aesthetic better than 4. Might as well standardize that
* I am now using vscode for Rust development, and am automatically running rustfmt on save, which enforced most of the styling changes in this PR
* I also ran clippy and lifted some needless mutability and ownership requirements.
Some of these rules can likely be enhanced with better values down the line, but I find it to be a good start.

rustfmt, clippy suggestions

---

CHANGELOG.md
src/c_signatures.rs
src/tree.rs
tests/base_tests.rs

Hey @triptec , let me know if you can quickly review this PR.
I very quickly added a couple of free methods for nodes and namespaces to allow for some workarounds until we can adapt your work for a 0.2 release and have the crate auto-free on drop.
Need to make some quick progress, as I recall you had to some time back, and this is the most conservative approach I could take - just adding a couple of methods

workaround free methods, v0.1.2

---

CHANGELOG.md
examples/tree_example.rs
src/tree/document.rs
src/tree/mod.rs
src/tree/namespace.rs
src/tree/node.rs
src/tree/nodetype.rs

For @triptec to quickly review - I went ahead and split out the four individual sub-modules of tree into their own Rust files, and organized them via `tree/mod.rs`.
The node implementation is still too large, but can last a bit longer as-is now. Feel free to take a quick look.
Aside: Additionally, I refactored 3 repositories that I have which work with rust-libxml to the latest master, and the edits were quite manageable - was done in 30 minutes with all 3. So the new API feels good-to-go in that regard. Still to profile for memory leaks there, but that will be my next PR.

Enhance tree modularity

---

CHANGELOG.md
src/tree/mod.rs
src/tree/node.rs
tests/mutability_guards.rs

As it so happens, one of my private projects using the grate hit an error with an Rc strong count of 5 (five)! Which was shocking.
One of the techniques I use there is legitimate - I am similarly bookkeeping nodes as a "current insertion point" during a document construction traversal that keeps absorbing content and moving up-and-down the tree as appropriate.
So I would expect an Rc strong count of at least 3 to be acceptable. And possibly even 5 with the specific function in question. The code is pretty directly ported from Perl's use of Nodes in XML::LibXML, and naturally Perl allows the mutability conflicts without any concern. I could try to completely rework that bit of code, and that may be a good idea for new projects, but for now I would prefer to have the simple option of …

Allow for higher Rc count mutability treshold

---

CHANGELOG.md
Cargo.toml
src/parser.rs
src/tree/document.rs
src/tree/node.rs
src/xpath.rs
tests/xpath_tests.rs

This came up in my recent work, I need a direct `node.findnodes()` call without having to worry about reusing a document-level context.
Allowed for refactoring a bit the Context struct, now using the more correct `DocumentRef` object, and staying away from the rather elaborate Document drop logic.
Added a couple of findnodes tests, and valgrind seems happy that no memory is leaked. So I'll just ship a minor release and take it from there.

Allow for direct node.findnodes calls without explicit context creation

---

src/tree/document.rs
src/tree/mod.rs
src/tree/node.rs
src/xpath.rs

CC @triptec , would be good to get a review if you have some a bit of time on your hands.
The story here is as follows. I hit [memory leak problems](https://github.com/KWARC/llamapun/issues/20) in one of the projects I have using rust-libxml, where I have a `corpus-level iterator` that traverses multiple documents, and parses them into libxml as you `.next()` through the iterator.
Before the big Node refactor, that code worked very elegantly, in almost constant memory, and gracefully deallocated each libxml2 Document (and its sub-objects) as the iterator proceeded to the next one. After, I observed memory leaking, as (a portion of) the allocated memory for each document remained present for the full run. 
I had some suspicions and indeed - it turned out that the `Rc<>` wrappers ended up …

Downgrade Node, Context and Object document references to Weak

---

src/tree/document.rs
src/tree/node.rs
src/xpath.rs
tests/VALGRIND.md
tests/tree_tests.rs

cc @triptec - another one to review.
I got lucky and found the trick to running valgrind in my other project (which keeps evolving as new features appear in nightly), more in [the issue](https://github.com/KWARC/llamapun/issues/20) for anyone interested.
And that revealed that using `Node::mock()` in an implementation of the `Default` trait is leaking memory - albeit tiny amounts.
So in this PR I finally did the C approach properly - I added `Node::null()` method, which uses a `ptr::null_mut`, and added an internal sibling of that method for `DocumentRef`. So now there is a memory-free placeholder node, which is more appropriate for my use case.
One could argue that the other project has an API mistake, and should really use an `Option<Node>` instead, but that makes the entire API way too …

Node::null, and clippy lints

---

.travis.yml
CHANGELOG.md
Cargo.toml
build.rs
examples/tree_example.rs
examples/xpath_example.rs
src/c_helpers.rs
src/lib.rs
src/parser.rs
src/tree/document.rs
src/tree/mod.rs
src/tree/namespace.rs
src/tree/node.rs
src/xpath.rs
tests/base_tests.rs
tests/mutability_guards.rs
tests/tree_tests.rs
tests/xpath_tests.rs

The 2018 edition is now in Rust stable:
https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html
Decided to update my crates and version bump, adding this for a Travis check.

update to 2018 edition of Rust

---

CHANGELOG.md
Cargo.toml
src/tree/node.rs
tests/tree_tests.rs

Simple replacement method for swapping a child node with a new node, inspired while porting code using Perl's `XML::LibXML`.
Would need more boilerplate to handle all possible inputs, but shipping this as a quick minor release and keeping things moving. I wrote some basic sanity tests, basic usage pattern seems functional.

add replace_child_node method

---

src/c_helpers.rs

The problem is that `LIBXML_THREAD_ENABLED` changes the `xmlIndentTreeOutput` global from a simple global variable into a function call that returns an lvalue. The only proper way to detect and handle this is to just use the macro in C.
This patch adds c_wrappers.c and compiles it in the build.rs. I tested this with a recent nightly rust on Mac OS X 10.14 and Debian testing.

Fix compiling on Mac OS X 10.14 (and presumably anywhere else that LIBXML_THREAD_ENABLED is set)

---

src/tree/node.rs
tests/xpath_tests.rs

Fixes #50 , thanks to @caldwell for the report!
Our memory management strategy is a bit too subtle, since the timing criteria can start getting hard to trace when we have all of nodes, document and xpath nodesets interplaying.
The goal remains simple: we bookkeep all nodes in our rust `_Document` object, and avoid freeing any node individually, as long as they are linked to an owner document - we free the entire document on drop, and the nodes get cleaned up along with it. For unlinked nodes, the idea so far has been that we can safely call `xmlFreeNode` when they drop out of scope in Rust, and have them cleaned up. But that relied on us figuring out the ownership and timing of all related structs, so that an unlinked node is really only explicitly freed once (i.e. it's really unlinked). …

safely unlink xpath-obtained nodes

---

src/tree/document.rs
src/tree/node.rs

As a follow-up research on #51 , I got reminded that tree_tests were still leaking some memory, to be precise:
```
==69165== LEAK SUMMARY:
==69165==    definitely lost: 448 bytes in 4 blocks
==69165==    indirectly lost: 15 bytes in 3 blocks
==69165==      possibly lost: 0 bytes in 0 blocks
==69165==    still reachable: 1,094 bytes in 20 blocks
==69165==         suppressed: 0 bytes in 0 blocks
```
Some were caused by a problem I had commented on in `Node::get_namespaces`, that frankly I won't have time to address before it becomes critical in someone's application. But I felt particularly bad about nodes created via the various `new` methods in Rust leaking out, which one can trace to our `wrap` mechanism being incomplete.
New nodes are associated with a document, but not part of its tree …

Stricter memory management of new Nodes

---

CHANGELOG.md
Cargo.toml
benches/parsing_benchmarks.rs
src/lib.rs
src/readonly.rs
src/readonly/tree.rs
src/tree/document.rs
src/xpath.rs
tests/readonly_tests.rs

A simple and pragmatic take on a multi-threaded primitive (see #47 ). 
A benchmark on a huge 112 MB XML file with this PR reveals:
```
single thread DFS count
time:   [1.1032 s 1.1079 s 1.1120 s]                                     
single thread DFS count+length
time:   [1.3465 s 1.3498 s 1.3532 s]
read-only single thread DFS count
time:   [302.88 ms 303.53 ms 304.31 ms]
read-only single thread DFS count+length
time:   [534.57 ms 535.03 ms 535.71 ms]
read-only multi thread DFS count
time:   [33.617 ms 34.120 ms 34.625 ms]
read-only multi thread DFS count+length
time:   [51.574 ms 52.269 ms 52.765 ms]
```
Where the single thread uses the Node implementation of master, while the `read-only` and multi thread benchmarks use the new `RoNode` construct.
The pragmatics of the PR were:
* only …

RoNode: read-only parallelization with minimal overhead

---

src/tree/node.rs
tests/tree_tests.rs

`Node` has `get_attribute_ns` and `set_attribute_ns`, but no `remove_attribute_ns`. This PR implements `remove_attribute_ns`.

add remove_attribute_ns

---

CHANGELOG.md
src/parser.rs
tests/base_tests.rs

Fixes #85
To avoid too many `parse_file_with_` variants I included the encoding into the `ParserOptions`. Hope that is acceptable.

Add ParserOptions

---

src/readonly/tree.rs
src/tree/document.rs
src/tree/node.rs

Thank you for creating and continuing to maintain this brilliant crate! It is the only solution that allows me to seemlessly translate my `lxml`-dependent Python code, with a significant usage of XPath (on HTML), into Rust (I have no idea why it is less popular than the other buggy and functionally incomplete crates; although porting from C is less exciting than writing in pure Rust, I think being able to work robustly is more important).
I'm currently not familiar with C (and its porting to Rust) , but I'm learning. I look forward to contributing to the source code when I become competent in the future. For now, what I can do is to fix some typos in the docs and provide any bug reports.

fix typos in docs

---

src/bindings.rs

The recent versions of rustc are throwing warnings at some bindgen-generated tests, such as:
```
warning: dereferencing a null pointer
--> src/bindings.rs:17692:15
|
17692 |     unsafe { &(*(::std::ptr::null::<_xmlSchemaNotation>())).type_ as *const _ as usize },
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this code causes undefined behavior when executed
|
= note: `#[warn(deref_nullptr)]` on by default
```
This PR simply comments all of those tests out, as an experimental way out. I prefer that to disabling the warning, since the technique sounds dangerous enough to not rely on in general.

Remove tests using null pointer deref

---

src/tree/namespace.rs
src/tree/node.rs

Allows errors to be sent between threads safely. Fixes errors such as:
```
`(dyn std::error::Error + 'static)` cannot be sent between threads safely
|
= help: the trait `std::marker::Send` is not implemented for `(dyn std::error::Error + 'static)`
= note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
= note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + 'static)>`
```

Box errors with Send and Sync

---

src/error.rs
src/parser.rs
src/schemas/schema.rs
src/tree/document.rs
src/tree/node.rs
src/xpath.rs

With the exception of the [result unit lint](https://rust-lang.github.io/rust-clippy/master/index.html#result_unit_err), this PR should patch all new lints from the recent clippy.

01.2022 clippy lints

---

CHANGELOG.md
src/readonly/tree.rs
src/tree/node.rs
tests/tree_tests.rs

Another cosmetic upgrade, allowing to use the just slightly faster [xmlHasProp](https://web.mit.edu/afs.new/sipb/user/yoz/libxml2-2.7.3/doc/html/libxml-tree.html#xmlHasProp) libxml2 function when only interested in whether an attribute exists or not - without allocating the value in Rust.

Add support for has_attribute, has_attribute_ns

---

src/tree/document.rs

The title says it, this change fixes a memory leak when dealing with the serialization of a document back to string.

fixing a memory leak when converting the xml to a string

---

CHANGELOG.md
src/tree/node.rs
src/xpath.rs
tests/resources/ids.xml
tests/xpath_tests.rs

I needed a convenience helper for string-oriented XPath selectors, such as `.//@xml:id`
So I added a `findvalues` variant, based on [xmlXPathCastNodeToString](https://gnome.pages.gitlab.gnome.org/libxml2/devhelp/libxml2-xpath.html#xmlXPathCastNodeToString). 
Hopefully nothing tricky here, and maybe a good time to add a minor release to signal the wrapper is still alive.

add Context::findvalues, Node::findvalues

---

src/parser.rs

`no_warning` (64) is added twice, resulting in 128 (`pedantic`), so if you have `no_warning` set, you actually end up with `pedantic` :sweat_smile: 
The rest of this code is correct.

parser: Fix computed option flag values

---

src/parser.rs

For security reasons [1], the libxml2 library has a hardcoded limit of 10Mb for processing files.
The library offers the `XML_PARSE_HUGE` entry as part of the `xmlParserOption` enum to allow programmers to override this limit.
This option can be given to the `xmlReadMemory` function to allow the processing of files over the 10Mb limit.
This patch adds the `huge` option to the `ParserOptions` struct to allow rust-libxml parse with options functions to use this feature.
[1] https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-4226

Enable processing of files over 10Mb

---

build.rs

This PR add a (very small) improvment in case `LIBXML2` env value is misconfigured.
I've encountered this probleme while porting [Hurl](https://github.com/Orange-OpenSource/hurl) to [conda-forge](https://github.com/conda-forge) where `LIBXML2` value is set to "2.11". 
Before the PR:
```shell
$ export LIBXML2="2.11"
$ cargo build
Compiling libxml v0.3.3 (/Users/jc/Documents/Dev/rust-libxml)
error: failed to run custom build command for `libxml v0.3.3 (/Users/jc/Documents/Dev/rust-libxml)`
Caused by:
process didn't exit successfully: `/Users/jc/Documents/Dev/rust-libxml/target/debug/build/libxml-5bb5ffa4b9ec77c1/build-script-build` (exit status: 101)
--- stderr
thread 'main' panicked at build.rs:7:5:
assertion failed: p.is_file()
note: run with `RUST_BACKTRACE=1` environment variable to …
```

Display LIBXML2 env value on build errors.

---

CHANGELOG.md
src/readonly/tree.rs
src/tree/node.rs
tests/tree_tests.rs

The method `get_property_no_ns` was added to `Node` and `RoNode` in line with this [issue](https://github.com/KWARC/rust-libxml/issues/125).
The method `get_property` returns the value of the first property with a given local name, regardless of namespace. This can lead to undesirable results when an element has multiple properties with the same local name. For example, calling it with "bar" on the node below returns "NS BAR" instead of "BAR".
```XML
<foo xmlns:ns="http://example.com" ns:bar="NS BAR" bar="BAR" />
```
On the other hand, the method `get_property_no_ns` returns the value of the nonprefixed property.

Add get_property_no_ns to Node and RoNode

---

CHANGELOG.md
src/c_helpers.rs
src/readonly/tree.rs
src/tree/namespace.rs
src/tree/node.rs
tests/resources/file01_ns.xml
tests/tree_tests.rs

The method `get_properties_ns` was added to `Node` and `RoNode` in line with this [issue](https://github.com/KWARC/rust-libxml/issues/104).
It returns a `HashMap` of attribute values, which is indexed by tuples of the attributes and their namespaces.
The code is similar to that of `get_properties`. However, `get_properties` used unnecessary vector allocation `attr_names`, which is removed in the PR.
The indexing mentioned above required implementing the traits `Hash`, `PartialEq` and `Eq` for `Namespace`. These were implemented using the methods `get_prefix ` and `get_href` instead of `ns_ptr`. This choice does not affect the method `get_properties_ns` as a prefix is bound to a single namespace name in a given scope. However, this has the effect that the two namespaces declared below are …

Add get_properties_ns to Node and RoNode

---

CHANGELOG.md
src/readonly/tree.rs
src/tree/node.rs
tests/tree_tests.rs

This completes what started in another [PR](https://github.com/KWARC/rust-libxml/pull/127) by adding the node methods `has_property_no_ns`, `remove_property_no_ns` and `get_property_node_no_ns`. These methods target nonprefixed properties and are needed when an element has multiple properties with the same local name, as in the example below:
```XML
<foo xmlns:ns="http://example.com" ns:bar="NS BAR" bar="BAR" />
```
Also, the method `get_property_node_ns` was added.
There was no added functionality to be gained by introducing `set_property_no_ns` as the existing method `set_property` sets the value for an attribute with no namespace.
While this adds functionality, it seems too verbose and repetitive. More ideally, one should have two variants of each method. One only takes an attribute …

Add no_ns variants for Node and RoNode methods

---

src/bindings.rs
src/parser.rs

latest clippy lints

---

.gitignore
tests/base_tests.rs

This makes for a better separation between source code and test execution data. It is needed to make tests pass in a Debian build environment where the source directory is not writeable.

tests: avoid writing to the source directory of the crate

---

build.rs

Avoid layout evaluation of `max_align_t` by marking it as opaque in the bindgen configuration. This prevents an overflow (`16_usize - 24_usize`) on 32-bit targets such as i386.
This change fixes a build failure on Debian i386 reported here[1], on version 0.3.4.
This issue was triggered by bindgen attempting to compute the layout of `max_align_t`, which can vary across platforms and cause invalid assumptions when compiling for 32-bit architectures.
This was also reported in the past here[2].
[1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1103580
[2]: https://github.com/rust-lang/rust-bindgen/issues/1338

build: mark `max_align_t` as opaque to fix i386 build failure

---

.github/workflows/CI.yml
build.rs
src/c_helpers.rs
src/error.rs
src/schemas/common.rs

Fixes #147.
First, opening the PR just with the added CI job to demonstrate its failure (see [the logs](https://github.com/KWARC/rust-libxml/actions/runs/14570632785/job/40867153540)).
Then, fixing the build by detecting the libxml2 version via pkg-config and adapting the code accordingly.
Note that in my previous PR I generated the `default_bindings.rs` with libxml 2.9.14. We can also revisit this choice later, possibly introducing different default bindings for < 2.12 and for >= 2.12, letting the user select which one via some environment variable. It would also be good to introduce a similar auto-detection logic on Windows via `vcpkg`.

Compatibility with libxml2 >= 2.12

---

.github/workflows/CI.yml
src/default_bindings.rs
src/parser.rs
src/schemas/validation.rs
tests/schema_tests.rs

Fixes #153 . Fixes #107. Fixes #152 .
I am not too happy with this PR suggestion. I rearranged the schema validation test to ensure it runs single-threaded, since isolating the exact cause for the segfault wasn't sufficiently clear. I would have preferred keeping the test as-is and finding the global state to guard in libxml.
The schema validation work was contributed by @cbarber so if they have time to take a look at some later point, they're welcome to.
Related in theme, but not in actual code path, I added the `.call_once` idea from #107 , which was guarding this exact kind of issue in the main XML parser.

Patches for libxml >=2.12

---

src/default_bindings.rs
src/schemas/schema.rs
src/wrapper.h
tests/schema_tests.rs

`xmlSchemaParse` calls `xmlSchemaInitTypes`.
`xmlSchemaInitTypes` is a lazy function which is only intended to be called once for optimization purposes - but libxml2 doesn't do this in a thread-safe manner.  We wrap the call in a OnceLock so that it only ever needs to be invoked once - and will do it in a thread-safe way.
This is the alternative approach to PR #158.

Protect `xmlSchemaInitTypes` from thread-unsafe behaviour.

---

.github/workflows/windows.yml
Cargo.toml
README.md
build.rs
src/c_helpers.rs
src/parser.rs
src/readonly/tree.rs
src/tree/document.rs
src/tree/node.rs
src/xpath.rs
tests/base_tests.rs

This PR is an update and transfer of #134 
It was much harder to stabilize than I anticipated, but this should be good enough for v0.3.5.
If actual Windows developers are reading this at a later date, please feel welcome and encouraged to contribute further improvements to the CI recipe, as well as to the approach for dealing with xmlFree. I don't develop on Windows at all, so this PR was my best effort as an outsider.
The key observation that touches the actual wrapper code is that a few of the bindings-near code paths were not sufficiently portable to work in MinGW, hence they get gradually refactored.
Coming up with a CI recipe was quite difficult, but that was mostly due to my having no experience working in either Windows environment.

Support Mingw-w64, also with CI target
